- name: Git Clone
  shell: git clone https://github.com/LucasBello/Grafana.git

- name: Permissao da pasta
  shell: chmod -R +x Grafana/

- name: Instalacao Completa
  shell: ./Grafana/full_installation.sh