---
- name: install '{{ packages}}'
  yum: 
   name: '{{ packages }}'

- name: Iniciar DB Server
  systemd: state=started name=mariadb

- name: Script para proteger o banco de dados
  template: src=../templates/secure.sh.j2 dest='/tmp/secure.sh' mode=0755

- name: Checar se banco esta protegido
  stat: path='/tmp/secure_temp.log' 
  register: secure_temp_file

- name: Proteger banco
  shell: "/tmp/secure.sh > /tmp/secure_temp.log"
  register: secure_log
  when: secure_temp_file.stat.exists != true

###
- name: Criar um novo banco 'wikidatabase'
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: '{{ ROOT_PASSWORD }}'

- name: Criar o usuario do Wiki e fornecer permissoes para host wiki01
  mysql_user:
    name: "{{ wiki_db_user }}"
    password: "123456"
    host:  '10.0.1.10'
    priv: '{{ db_name }}.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: '{{ ROOT_PASSWORD }}'

- name: Criar o usuario do Wiki e fornecer permissoes para host wiki02
  mysql_user:
    name: "{{ wiki_db_user }}"
    password: "123456"
    host:  '10.0.2.20'
    priv: '{{ db_name }}.*:ALL,GRANT'
    state: present
    login_user: root
    login_password: '{{ ROOT_PASSWORD }}'


- name: Confirmacao da criacao
  shell: 'mysql -u root -p{{ ROOT_PASSWORD }} --execute="SHOW DATABASES;"'
  register: db_list

- name: Falha em criar
  fail: msg="Database was not created"
  when: db_name not in db_list.stdout_lines

- name: Habiltiar servico do MariaDB
  systemd:
    name: mariadb
    enabled: yes

- name: Liberar httpd reverso
  shell: sudo setsebool -P httpd_can_network_connect 1

- name: Git Clone
  shell: git clone https://github.com/LucasBello/Grafana.git

- name: Permissao da pasta
  shell: chmod -R +x Grafana/

- name: Instalacao Export_node
  shell: ./Grafana_rhel/node.sh