---
- name: Media Wiki Database, WebServer e Grafana
  hosts: all
  become: yes
  
  vars_files: 
    - vault.yml

  roles:
   - { role: mysqldb, tags: ['install_db'] }
   - { role: web, tags: [ 'install_web' ] }
   - { role: grafana, tags: [ 'install_grafana'] }     
